name: fuzzysearchrs

on:
  push:
    branches: ["main"]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
        
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v3  
    
      - name: Publish to crates.io
        run: |
          cargo login ${CRATES_IO_API_KEY}
          cargo publish
        env:
          CRATES_IO_API_KEY: ${{ secrets.CRATES_IO_API_KEY }}
